name: testcca
favicon: null
layout_spectrum: 0.8421699206810445
typography_spectrum: 0.3376838490366936
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5480403041001409
  lightness: 0.15796622354537249
  saturation: 0.15126454341225326
  rhythmicContrast: 0.26803790917620063
purpose: []
